package xforce.resource;

public final class Localization {
    public static final int LANG_ENGLISH = 0;
    public static final int LANG_VIETNAMESE = 1;
    public static int language = LANG_ENGLISH;
    public static String[] languageNames = {"ENG", "VIET"};
    public static int MENU_MAIN = 0;
    public static int MENU_CAREER = 1;
    public static int MENU_INSTRUCTIONS = 4;
    public static String[][] menuTexts;
    public static String[] pauseLabels;
    public static String[][] optionsTexts;
    public static String[] shopLabels;
    public static String txtSoundQuestion;
    public static String txtExitQuestion;
    public static String txtGoHomeQuestion;
    public static String txtNewGameQuestion;
    public static String txtOn;
    public static String txtOff;
    public static String txtYes;
    public static String txtNo;
    public static String txtBack;
    public static String txtNext;
    public static String txtSelect;
    public static String txtBuy;
    public static String txtGarage;
    public static String txtCareer;
    public static String txtShopping;
    public static String txtWorldMap;
    public static String txtCredits;
    public static String txtInstructions;
    public static String lblCash;
    public static String lblBonus;
    public static String lblXp;
    public static String lblPrice;
    public static String[] vehicleNames;
    public static String[] vehicleDescs;
    public static String[] welcomeDialogue;
    public static String txtPressAnyKey;
    public static String txtPress;
    public static String txtLoading;
    public static String txtMissionComplete;
    public static String txtMissionFail;
    public static String txtMission;
    public static String lblEnemyKilled;
    public static String txtInfo;
    public static String[] missionObjectives;
    public static String[] creditsLines;
    public static String helpText;
    public static String txtNa;
    public static String[] trainDialogue;
    public static String[] bossRunDialogue;
    public static String[] completeDialogue;
    public static String txtDestroyBoss;
    public static String txtDestroyAirport;
    public static String txtProtectVip;
    public static String txtWelcome;
    public static String txtUnlockVehicle;
    public static String txtNothingToUnlock;
    public static String txtGreatMission;
    public static String[] nickDialogue;
    public static String[] xpDialogue;
    public static String[] miaDialogue;
    public static String[] danDialogue;
    public static String txtNotEnoughXp;
    public static String txtNotEnoughMoney;
    public static String lblName;
    public static String lblPlayTime;
    public static String lblCompleted;
    public static String txtWhatsYourName;
    public static void init() {
        switch (language) {
            case 0:
                menuTexts = new String[][]{new String[]{"RESUME CAREER", "NEW CAREER", "OPTIONS", "CREDITS", "INSTRUCTIONS", "EXIT GAME"}, new String[]{"WORLD MAP", "SHOP", "GARAGE", "INFOMAIIONS", "", "BACK"}, new String[]{"SELECT <>", "INFO", "BACK"}, new String[]{"ENGINE", "GUN", "BODYER", "REPAIR", "MINES", "", "BACK"}, new String[]{"RESUME", "MISSION", "RESTART", "OPTIONS", "GO HOME"}, new String[]{"MUSIC: ", "SOUND: ", "VIBRATION: ", "AUTO SHOOT: ", "BACK"}};
                pauseLabels = new String[]{"RESUME", "MISSION", "OPTIONS", "GO HOME"};
                optionsTexts = new String[][]{new String[]{"MUSIC: ", "SOUND: ", "VIBRATION: ", "CONTROL", "LANGUAGE: ", "BACK"}, new String[]{"SELECT/FIRE: ", "PUT DYNAMIC: ", "PUT MINE: ", "AUTO SHOOT: ", "BACK"}};
                shopLabels = new String[]{"ENGINE", "GUN", "BODYER", "REPAIR", "DYNAMIC", "MINE"};
                txtSoundQuestion = "DO YOU WANT SOUND ?";
                txtExitQuestion = "DO YOU WANT TO EXIT GAME ?";
                txtGoHomeQuestion = "GO HOME, YOU WILL BE LOSE!\nARE YOU SURE?";
                txtNewGameQuestion = "DO YOU WANT TO START A NEW CAREER ?\nALL PREVIOUS DATA WILL BE DELETE.";
                txtOn = "ON";
                txtOff = "OFF";
                txtYes = "YES";
                txtNo = "NO";
                txtBack = "BACK";
                txtNext = "NEXT";
                txtSelect = "SELECT";
                txtBuy = "BUY";
                txtGarage = "GARAGE";
                txtCareer = "CAREER";
                txtShopping = "SHOPPING";
                txtWorldMap = "WORLD MAP";
                txtCredits = "CREDITS";
                txtInstructions = "INSTRUCTIONS";
                lblCash = "CASH: ";
                lblBonus = "BONUS: ";
                lblXp = "XP: ";
                lblPrice = "PRICE: ";
                vehicleNames = new String[]{"H5 ULTIMATE", "CERBERUS III", "APACHE NIGHTMARE"};
                vehicleDescs = new String[]{"WITH A 180HP 4-CYLINDER DIESEL ENGINE, TOP SPEEDS OF 120KM/H, WEIGHT: 4.0 TONS, 5.56MM MINIMI MACHINE GUN OR LIGHT ANTI-TANK GUIDED MISSILE", "INCLUDING 120MM SMOOTHBORE MAIN GUN, LASER RANGE FINDER, INFRARED NIGHT VIEWER, AUTOMATIC CANNON LOADING SYSTEM, 7.62MM MACHINE GUN AND AUTO ANTI-AIR MISSILES SYSTEM AND HUSKUDA V12 ENGINE", "T780-GE-709C ENGINES, HYDRA 90 FFAR ROCKETS MISSILES: COMBINATION OF AGM-114 HELLFIRE, AIM-92 STINGER, AIM-9 SIDEWINDER "};
                txtPressAnyKey = "PRESS ANY KEY";
                txtPress = "PRESS...";
                txtLoading = "LOADING...";
                txtMissionComplete = "MISSION COMLETE";
                txtMissionFail = "MISSION FAIL";
                txtMission = "MISSION";
                lblEnemyKilled = "ENEMY KILLED: ";
                txtInfo = "INFOMATION";
                txtNa = "N/A";
                missionObjectives = new String[]{"- DESTROY ALL ENEMIES", "- DESTROY THE TRAIN", "- DESTROY THE SHIP", "- DESTROY THE SHIP\n- KILL THE BIG BOSS", "- KILL THE BIG BOSS", "- DESTROY THE BIG TANK", "- DESTROY ALL ENEMIES\n- DESTROY THE AIRPORT", "- PROTECT VIP'S CAR", "- PROTECT VIP'S CAR", "- PROTECT VIP'S CAR"};
                creditsLines = new String[]{"PRODUCER", "TEA-M CORP.", "RELEASE 2008", "", "OTHER GAMES", "ESCAPE", "NINJA SCHOOL", "GALAXY BUILDER", "LINE 2", "NEO CHESS", "", "SPECIAL THANKS", "FMA", "E-CHIP MOBILE", "LED-MOBILE", "T-ROCK", "", "VISIT OUR HOMEPAGE", "VECHAI321.XTGEM.COM", "VECHAI321.XTGEM.COM"};
                helpText = "XFORCE\nTHE PROFESSIONAL\nMILITARY, SECURITY,\nPEACE KEEPING, LAW\nENFORCEMENT COMPANY.\n\nVISION:\nTO SUPPORT SECURITY,\nPEACE, FREEDOM, AND\nDEMOCRACY EVERYWHERE.\n\nCONTROLER:\nUSE THE D-PAD OR\ufffd\n4: MOVE LEFT\n6: MOVE RIGHT\n2: MOVE UP\n8: MOVE DOWN\n5: FIRE\n0: SET THE DYNAMIC\n\nREMEMBER CHECK YOUR\nVEHICLE BEFORE YOU\nCHOOSE THE MISSION.\n\nTHE MORE ENEMY YOU\nDESTROYED, THE MORE\nXP POINTS YOU GOT.";
                trainDialogue = new String[]{"Listen, your task is destroy the train. It will run in next 5 mins.", "yes sir, but how...", "go here to get the dynamite...", "then, put it here and get out...", "now let go..."};
                bossRunDialogue = new String[]{"Oh no...", "I will go there now, wait...", "You come, Try to kill him now..."};
                completeDialogue = new String[]{"done...", "Good job...", "....", "....", "...."};
                txtDestroyBoss = "Destroy him now";
                txtDestroyAirport = "Destroy all fighter in the Airport";
                txtProtectVip = "Protect him to safe point";
                txtWelcome = "Wellcom to XForce team. Many thing waiting for you.";
                txtUnlockVehicle = "You unlock new vehical. Go to my garage and get it now";
                txtNothingToUnlock = "Congratulations, you have nothing to unlock.";
                txtGreatMission = "Congratulations, you have just complete a great mission.";
                welcomeDialogue = new String[]{"I see you are back. Good decision!", "Finally you are here! The others started to worry about you.", "Huh!! Later better than never"};
                nickDialogue = new String[]{"Hi, my name's Nicholas Craven. Nice to meet you.", "Go out for drink now, ha ha..."};
                xpDialogue = new String[]{"My name's Xavier Peugeot, call name XP. I will support you.", "No time for relax."};
                miaDialogue = new String[]{"Hi, my name's Mia Montaya, I'm a excellent pilot. I wanna make friend with you", "Go out with me please!", "I'm lonely, you make me happy.", "Baby want more time !!!"};
                danDialogue = new String[]{"Hello, I'm Dan Smith, mechanic. I have everything you want.", "Repair your vehical now if you don't want to lose.", "Ha ha. What do you want officer ?..."};
                txtNotEnoughXp = "Not enough xp";
                txtNotEnoughMoney = "Not enough money";
                lblName = "NAME: ";
                lblPlayTime = "PLAY TIME: ";
                lblCompleted = "GAME COMLETED: ";
                txtWhatsYourName = "What 's your name ?";
                break;
            case 1:
                menuTexts = new String[][]{new String[]{"TI\u1ebeP T\u1ee4C", "CH\u01a0I M\u1edaI", "L\u1ef0A CH\u1eccN", "T\u00c1C GI\u1ea2", "TH\u00d4NG TIN", "THO\u00c1T"}, new String[]{"B\u1ea2N \u0110\u1ed2", "C\u1eecA H\u00c0NG", "GARA", "TH\u00d4NG TIN", "", "TR\u1ede V\u1ec0"}, new String[]{"CH\u1eccN <>", "INFO", "BACK"}, new String[]{"M\u00c1Y", "S\u00daNG", "TH\u00c2N", "S\u1eecA CH\u1eeeA", "TNT", "", "TR\u1ede V\u1ec0"}, new String[]{"TR\u1ede V\u1ec0", "NHI\u1ec6M V\u1ee4", "RESTART", "L\u1ef0A CH\u1eccN", "V\u1ec0 NH\u00c0"}, new String[]{"NH\u1ea0C N\u1ec0N: ", "\u00c2M THANH: ", "RUNG: ", "T\u1ef0 B\u1eaeN: ", "TR\u1ede V\u1ec0"}};
                pauseLabels = new String[]{"TR\u1ede L\u1ea0I", "NHI\u1ec6M V\u1ee4", "TU\u1ef2 CH\u1eccN", "V\u1ec0 C\u0102N C\u1ee8"};
                optionsTexts = new String[][]{new String[]{"NH\u1ea0C: ", "TI\u1ebeNG \u0110\u1ed8NG: ", "RUNG: ", "\u0110I\u1ec0U KHI\u1ec2N", "NG\u00d4N NG\u1eee: ", "TR\u1ede V\u1ec0"}, new String[]{"CH\u1eccN/B\u1eaeN: ", "\u0110\u1eb6T THU\u1ed0C N\u1ed4: ", "\u0110\u1eb6T M\u00ccN: ", "B\u1eaeN T\u1ef0 \u0110\u1ed8NG: ", "TR\u1ede V\u1ec0"}};
                shopLabels = new String[]{"M\u00c1Y", "HO\u1ea2 L\u1ef0C", "TH\u00c2N", "S\u1eecA CH\u1eecA", "CH\u1ea4T N\u1ed4", "M\u00ccN"};
                txtSoundQuestion = "B\u1ea0N MU\u1ed0N M\u1ede \u00c2M THANH ?";
                txtExitQuestion = "B\u1ea0N C\u00d3 MU\u1ed0N THO\u00c1T GAME ?";
                txtGoHomeQuestion = "TR\u1ede V\u1ec0 C\u0102N C\u1ee8 B\u1ea0N S\u1ebc THUA!\nB\u1ea0N QUY\u1ebeT \u0110\u1ecaNH V\u1ec0 CH\u1ee8?";
                txtNewGameQuestion = "B\u1ea0N C\u00d3 MU\u1ed0N T\u1ea0O PROFILE M\u1edaI ?\nC\u00c1C TH\u00d4NG TIN C\u0168 S\u1ebc B\u1eca XO\u00c1.";
                txtOn = "M\u1ede";
                txtOff = "T\u1eaeT";
                txtYes = "C\u00d3";
                txtNo = "KH\u00d4NG";
                txtBack = "TR\u1ede L\u1ea0I";
                txtNext = "TI\u1ebeP";
                txtSelect = "CH\u1eccN";
                txtBuy = "MUA";
                txtGarage = "GARAGE";
                txtCareer = "NGH\u1ec0 NGHI\u1ec6P";
                txtShopping = "N\u00c2NG C\u1ea4P";
                txtWorldMap = "B\u1ea2N \u0110\u1ed2";
                txtCredits = "NG\u01af\u1edcI PH\u00c1T TRI\u1ec2N";
                txtInstructions = "GI\u1edaI THI\u1ec6U";
                lblCash = "TI\u1ec0N: ";
                lblBonus = "TH\u01af\u1edeNG: ";
                lblXp = "XP: ";
                lblPrice = "GI\u00c1: ";
                vehicleNames = new String[]{"H5 ULTIMATE", "CERBERUS III", "APACHE HUSKUS"};
                vehicleDescs = new String[]{"\u0110\u1ed8NG C\u01a0 DIESEL 180 M\u00c3 L\u1ef0C 4-XILANH, V\u1eacN T\u1ed0C T\u1ed0I \u0110A 150KM/H,TR\u1eccNG L\u01af\u1ee2NG : 4.0 T\u1ea4N, S\u00daNG M\u00c1Y 5.56MM V\u00c0 T\u00caN L\u1eecA CH\u1ed0NG T\u0102NG T\u1ea6M NHI\u1ec6T", "\u0110\u01af\u1ee2C TRANG B\u1eca \u0110\u1ea0I B\u00c1C HUSUDINS, LASER M\u1eaeT TH\u1ea6N \u0110\u1ecaNH V\u1eca, QUAN S\u00c1T \u0110\u00caM H\u1ed2NG NGO\u1ea0I, H\u1ec6 TH\u1ed0NG T\u1ef0 \u0110\u1ed8NG N\u1ea0P \u0110\u1ea0N, S\u00daNG M\u00c1Y 7.62MM, T\u00caN L\u1eecA CH\u1ed0NG T\u0102NG V\u00c0 PH\u00d2NG KH\u00d4NG, \u0110\u1ed8NG C\u01a0 HUSKUDA V12", "\u0110\u1ed8NG C\u01a0 T780-GE-709C, T\u00caN L\u1eecA T\u1ea6M NHI\u1ec6T HYDRA 90 FFAR: K\u1ebeT H\u1ee2P V\u1edaI H\u1ec6 TH\u1ed0NG AGM-114 HELLFIRE, AIM-92 STINGER, AIM-9 SIDEWINDER "};
                txtPressAnyKey = "NHAN PHIM BAT KY";
                txtPress = "NH\u1ea4N...";
                txtLoading = "DANG TAI...";
                txtMissionComplete = "NV HO\u00c0N TH\u00c0NH";
                txtMissionFail = "NV TH\u1ea4T B\u1ea0I";
                txtMission = "NHI\u1ec6M V\u1ee4";
                lblEnemyKilled = "TI\u00caU DI\u1ec6T: ";
                txtInfo = "TH\u00d4NG TIN";
                txtNa = "KH\u00d4NG H\u1ee2P L\u1ec6";
                missionObjectives = new String[]{"- TI\u00caU DI\u1ec6T TO\u00c0N B\u1ed8 QU\u00c2N \u0110\u1ecaCH", "- PH\u00c1 HU\u1ef6 \u0110O\u00c0N T\u00c0U HO\u1ea2", "- PH\u00c1 HU\u1ef6 T\u00c0U CHI\u1ebeN \u0110\u1ecaCH", "- PH\u00c1 HU\u1ef6 T\u00c0U CHI\u1ebeN \u0110\u1ecaCHP\n- GI\u1ebeT TR\u00d9M", "- TI\u00caU DI\u1ec6T XE T\u0102NG ULTRA TANK 34", "- TI\u00caU DI\u1ec6T XE T\u0102NG L\u1edaN ", "- TI\u00caU DI\u1ec6T \u0110\u1ecaCH\n- PH\u00c1 HU\u1ef6 S\u00c2N BAY", "- B\u1ea2O V\u1ec6 XE C\u1ee6A VIP", "- B\u1ea2O V\u1ec6 XE C\u1ee6A VIP", "- B\u1ea2O V\u1ec6 XE C\u1ee6A VIP"};
                creditsLines = new String[]{"S\u1ea2N XU\u1ea4T", "TEA-M GROUP", "PH\u00c1T H\u00c0NH 2008", "", "GAMES KH\u00c1C", "ESCAPE", "NINJA SCHOOL", "GALAXY BUILDER", "LINE 2", "NEO CHESS", "", "G\u1edeI L\u1edcI C\u1ea2M \u01a0N \u0110\u1ebeN", "FMA", "E-CHIP MOBILE", "LED-MOBILE", "T-ROCK", "", "THAM QUAN WEBSITE", "VECHAI321.XTGEM.COM", "VECHAI321.XTGEM.COM"};
                helpText = "XFORCE\nTHE PROFESSIONAL\nMILITARY, SECURITY,\nPEACE KEEPING, LAW\nENFORCEMENT COMPANY.\n\nVISION:\nTO SUPPORT SECURITY,\nPEACE, FREEDOM, AND\nDEMOCRACY EVERYWHERE.\n\nCONTROLER:\nUSE THE D-PAD OR\ufffd\n4: MOVE LEFT\n6: MOVE RIGHT\n2: MOVE UP\n8: MOVE DOWN\n5: FIRE\n0: SET THE DYNAMIC\n\nREMEMBER CHECK YOUR\nVEHICLE BEFORE YOU\nCHOOSE THE MISSION.\n\nTHE MORE ENEMY YOU\nDESTROYED, THE MORE\nXP POINTS YOU GOT.";
                trainDialogue = new String[]{"Alo.. Nhi\u1ec7m v\u1ee5 c\u1ee7a anh l\u00e0 ph\u00e1 h\u1ee7y xe l\u1eeda ch\u1edf v\u0169 kh\u00ed h\u1ea1t nh\u00e2n n\u00e0y. N\u00f3 s\u1ebd kh\u1edfi h\u00e0nh trong 5 ph\u00fat n\u1eefa. N\u00f3 r\u1ea5t nguy hi\u1ec3m \u0111\u1ec3 ti\u1ebfp c\u1eadn v\u00e0 ph\u00e1 h\u1ee7y, t\u00f4i s\u1ebd h\u01b0\u1edbng d\u1eabn anh th\u1eadt chi ti\u1ebft", "V\u00e2ng, v\u1eady t\u00f4i ph\u1ea3i l\u00e0m c\u00e1ch n\u00e0o", "H\u00e3y \u0111\u1ebfn \u0111\u00e2y \u0111\u1ec3 l\u1ea5y m\u00ecn, \u0111\u00e2y l\u00e0 lo\u1ea1i m\u00ecn \u0111\u1eb7t bi\u1ec7t v\u00e0 c\u1ea7n thi\u1ebft cho nhi\u1ec7m v\u1ee5 n\u00e0y", "\u0110\u1eb7t m\u00ecn t\u1ea1i \u0111\u01b0\u1eddng ray ch\u1ed7 n\u00e0y, n\u01a1i \u0111o\u00e0n tau s\u1ebd \u0111i qua. Xong h\u00e3y r\u1eddi kh\u1ecfi \u0111\u00f3.", "S\u1eafp \u0111\u1ebfn gi\u1edd r\u1ed3i, kh\u1ea9n tr\u01b0\u01a1ng l\u00ean. Ch\u00fac may m\u1eafn..."};
                bossRunDialogue = new String[]{"M\u1eb9 ki\u1ebfp... H\u1eafn \u0111\u00e3 b\u1ecf ch\u1ea1y m\u1ea5t r\u1ed3i.", "\u0110\u1eebng lo, em s\u1ebd \u0111\u1ebfn ngay.", "Ah, c\u00f4 \u0111\u00e3 \u0111\u1ebfn r\u1ed3i, h\u00e3y \u0111u\u1ed5i theo ngay, \u0111\u1eebng \u0111\u1ec3 h\u1eafn tho\u00e1t."};
                completeDialogue = new String[]{"Ha ha, ch\u00fang ta \u0111\u00e3 th\u00e0nh c\u00f4ng r\u1ed3i.", "T\u1ed1t l\u1eafm, c\u00e1c anh th\u1eadt x\u1ee9ng \u0111\u00e1ng.", "C\u00f2n ch\u1edd g\u00ec n\u1eefa, \u0103n m\u1eebng th\u00f4i, t\u00f4i s\u1ebd \u0111\u00e3i ch\u1ea7u nh\u1eadu chi\u1ec1u nay.", "Th\u1ebf c\u00f2n t\u0103ng 2 l\u00e0 g\u00ec, ai ph\u1ee5 tr\u00e1ch \u0111\u00e2y", "T\u1edbi \u0111\u00f3 r\u1ed3i t\u00ednh, he he..."};
                txtDestroyBoss = "H\u00e3y gi\u1ebft xe t\u0103ng tr\u00f9m n\u00e0y.";
                txtDestroyAirport = "h\u00e3y ph\u00e1 h\u1ee7y t\u1ea5t c\u1ea3 m\u00e1y bay chi\u1ebfn \u0111\u1ea5u trong s\u00e2n bay n\u00e0y. H\u00e3y c\u1ea9n th\u1eadn, ch\u00fang s\u1ebd ph\u1ea3n c\u00f4ng r\u1ea5t d\u1eef d\u1ed9i.";
                txtProtectVip = "H\u00e3y b\u1ea3o v\u1ec1 xe VIP n\u00e0y \u0111\u1ebfn n\u01a1i an to\u00e0n.";
                txtWelcome = "Ch\u00e0o m\u1eebng \u0111\u1ebfn v\u1edbi \u0111\u1ed9i XForce. Ch\u00fang t\u00f4i \u0111ang ch\u1edd anh \u0111\u00e2y.";
                txtUnlockVehicle = "Anh \u0111\u00e3 unlock kh\u00ed t\u00e0i m\u1edbi";
                txtNothingToUnlock = "Ch\u00fac m\u1eebng, nh\u01b0ng r\u1ea5t ti\u1ebfc kh\u00f4ng c\u00f2n g\u00ec m\u1edbi n\u1eefa :)";
                txtGreatMission = "Ch\u00fac m\u1eebng, anh v\u1eeba ho\u00e0n th\u00e0nh m\u1ed9t nhi\u1ec7m v\u1ee5 l\u1edbn";
                welcomeDialogue = new String[]{"\u0110\u1ebfn tr\u1ec5 c\u00f2n h\u01a1n kh\u00f4ng. M\u1eddi anh ng\u1ed3i!", "Cu\u1ed1i c\u00f9ng c\u0169ng \u0111\u1ebfn! T\u00f4i t\u01b0\u1edfng anh ch\u1ebft r\u1ed3i.", "Huh!! Anh ngh\u0129 anh l\u00e0 ai, ng\u1ed3i xu\u1ed1ng"};
                nickDialogue = new String[]{"Ch\u00e0o, m\u00ecnh l\u00e0 Nicholas Craven. M\u1ecdi ng\u01b0\u1eddi v\u1eabn g\u1ecdi l\u00e0 Nick. R\u1ea5t vui \u0111\u01b0\u1ee3c g\u1eb7p b\u1ea1n.", "Xong r\u1ed3i m\u00ecnh s\u1ebd \u0111i u\u1ed1ng cho th\u1eadt \u0111\u00e3 nh\u00e9, ha ha...", "M\u00ecnh bi\u1ebft m\u1ed9t ch\u1ed5 \u0111\u00e1nh bida hay l\u1eafm, m\u1ea5y em s\u1eafp bi tuy\u1ec7t v\u1eddi."};
                xpDialogue = new String[]{"T\u00f4i l\u00e0 Xavier Peugeot, th\u01b0\u1eddng g\u1ecdi l\u00e0 XP. T\u00f4i s\u1ebd h\u1ed5 tr\u1ee3 anh.", "Kh\u00f4ng c\u00f3 th\u1eddi gian \u0111\u1ec3 ngh\u1ec9 ng\u01a1i \u0111\u00e2u.", "T\u00f4i kh\u00f4ng c\u1ea7n \u0111i massa \u0111\u00e2u, anh \u0111i m\u1ed9t m\u00ecnh \u0111i."};
                miaDialogue = new String[]{"Hi, em l\u00e0 Mia Montaya, l\u00e0 m\u1ed9t phi c\u00f4ng c\u1eeb kh\u00f4i. Em r\u1ea5t mu\u1ed1n l\u00e0m b\u1ea1n v\u1edbi anh.", "T\u1ed1i nay \u0111i ch\u01a1i v\u1edbi em nh\u00e9! hi hi...", "R\u1ea5t vui khi l\u1ea1i \u0111\u01b0\u1ee3c g\u1eb7p anh.", "Kh\u00f4ng y\u00eau \u0111\u1eebng n\u00f3i l\u1eddi cay \u0111\u1eafng !!!"};
                danDialogue = new String[]{"Xin ch\u00e0o, t\u00f4i l\u00e0 th\u1ee3 m\u00e1y Dan Smith. T\u00f4i lu\u00f4n c\u00f3 m\u1ecdi th\u1ee9 anh mu\u1ed1n.", "H\u00e3y s\u1eefa xe ngay n\u1ebfu anh kh\u00f4ng mu\u1ed1n b\u1ecb th\u1ea5t b\u1ea1i.", "Ha ha. Anh mu\u1ed1n g\u00ec h\u1ea3 \u0111\u1ed3ng ch\u00ed ? ..."};
                txtNotEnoughXp = "Kh\u00f4ng \u0111\u1ee7 \u0111i\u1ec3m kinh nghi\u1ec7m";
                txtNotEnoughMoney = "Kh\u00f4ng \u0111\u1ee7 ti\u1ec1n";
                lblName = "T\u00caN: ";
                lblPlayTime = "GI\u1edc CH\u01a0I: ";
                lblCompleted = "HO\u00c0N TH\u00c0NH: ";
                txtWhatsYourName = "Anh t\u00ean g\u00ec ?";
                break;
        }
    }
}
