package defpackage;

/* JADX INFO: loaded from: XForce.jar:al.class */
public final class al {
    public static int a = 0;
    public static String[] b = {"ENG", "VIET"};
    public static int c = 0;
    public static int d = 1;
    public static int e = 4;
    public static String[][] f;
    public static String[] g;
    public static String[][] h;
    public static String[] i;
    public static String j;
    public static String k;
    public static String l;
    public static String m;
    public static String n;
    public static String o;
    public static String p;
    public static String q;
    public static String r;
    public static String s;
    public static String t;
    public static String u;
    public static String v;
    public static String w;
    public static String x;
    public static String y;
    public static String z;
    public static String A;
    public static String B;
    public static String C;
    public static String D;
    public static String E;
    public static String[] F;
    public static String[] G;
    public static String[] H;
    public static String I;
    public static String J;
    public static String K;
    public static String L;
    public static String M;
    public static String N;
    public static String O;
    public static String P;
    public static String[] Q;
    public static String[] R;
    public static String S;
    public static String T;
    public static String[] U;
    public static String[] V;
    public static String[] W;
    public static String X;
    public static String Y;
    public static String Z;
    public static String aa;
    public static String ab;
    public static String ac;
    public static String ad;
    public static String[] ae;
    public static String[] af;
    public static String[] ag;
    public static String[] ah;
    public static String ai;
    public static String aj;
    public static String ak;
    public static String al;
    public static String am;
    public static String an;

    public static void a() {
        switch (a) {
            case 0:
                f = new String[][]{new String[]{"RESUME CAREER", "NEW CAREER", "OPTIONS", "CREDITS", "INSTRUCTIONS", "EXIT GAME"}, new String[]{"WORLD MAP", "SHOP", "GARAGE", "INFOMAIIONS", "", "BACK"}, new String[]{"SELECT <>", "INFO", "BACK"}, new String[]{"ENGINE", "GUN", "BODYER", "REPAIR", "MINES", "", "BACK"}, new String[]{"RESUME", "MISSION", "RESTART", "OPTIONS", "GO HOME"}, new String[]{"MUSIC: ", "SOUND: ", "VIBRATION: ", "AUTO SHOOT: ", "BACK"}};
                g = new String[]{"RESUME", "MISSION", "OPTIONS", "GO HOME"};
                h = new String[][]{new String[]{"MUSIC: ", "SOUND: ", "VIBRATION: ", "CONTROL", "LANGUAGE: ", "BACK"}, new String[]{"SELECT/FIRE: ", "PUT DYNAMIC: ", "PUT MINE: ", "AUTO SHOOT: ", "BACK"}};
                String[] strArr = {"SELECT <>", "INFO", "BACK"};
                i = new String[]{"ENGINE", "GUN", "BODYER", "REPAIR", "DYNAMIC", "MINE"};
                String[] strArr2 = {"SPEED", "POWER", "ARMOUR"};
                j = "DO YOU WANT SOUND ?";
                k = "DO YOU WANT TO EXIT GAME ?";
                l = "GO HOME, YOU WILL BE LOSE!\nARE YOU SURE?";
                m = "DO YOU WANT TO START A NEW CAREER ?\nALL PREVIOUS DATA WILL BE DELETE.";
                n = "ON";
                o = "OFF";
                p = "YES";
                q = "NO";
                r = "BACK";
                s = "NEXT";
                t = "SELECT";
                u = "BUY";
                v = "GARAGE";
                w = "CAREER";
                x = "SHOPPING";
                y = "WORLD MAP";
                z = "CREDITS";
                A = "INSTRUCTIONS";
                B = "CASH: ";
                C = "BONUS: ";
                D = "XP: ";
                E = "PRICE: ";
                F = new String[]{"H5 ULTIMATE", "CERBERUS III", "APACHE NIGHTMARE"};
                G = new String[]{"WITH A 180HP 4-CYLINDER DIESEL ENGINE, TOP SPEEDS OF 120KM/H, WEIGHT: 4.0 TONS, 5.56MM MINIMI MACHINE GUN OR LIGHT ANTI-TANK GUIDED MISSILE", "INCLUDING 120MM SMOOTHBORE MAIN GUN, LASER RANGE FINDER, INFRARED NIGHT VIEWER, AUTOMATIC CANNON LOADING SYSTEM, 7.62MM MACHINE GUN AND AUTO ANTI-AIR MISSILES SYSTEM AND HUSKUDA V12 ENGINE", "T780-GE-709C ENGINES, HYDRA 90 FFAR ROCKETS MISSILES: COMBINATION OF AGM-114 HELLFIRE, AIM-92 STINGER, AIM-9 SIDEWINDER "};
                String[] strArr3 = {"NAME: NICHOLAS CRAVEN \nNICKNAME: NICK\nAGE: 26\nFORTE: JEEP DRIVER", "NAME: XAVIER PEUGEOT\nNICKNAME: XP\nAGE: 35\nFORTE: TANK DRIVER", "NAME: MIA MONTAYA\nNICKNAME: KAMIKAYE\nAGE: 25\nFORTE: PILOT"};
                I = "PRESS ANY KEY";
                J = "PRESS...";
                K = "LOADING...";
                L = "MISSION COMLETE";
                M = "MISSION FAIL";
                N = "MISSION";
                O = "ENEMY KILLED: ";
                P = "INFOMATION";
                T = "N/A";
                Q = new String[]{"- DESTROY ALL ENEMIES", "- DESTROY THE TRAIN", "- DESTROY THE SHIP", "- DESTROY THE SHIP\n- KILL THE BIG BOSS", "- KILL THE BIG BOSS", "- DESTROY THE BIG TANK", "- DESTROY ALL ENEMIES\n- DESTROY THE AIRPORT", "- PROTECT VIP'S CAR", "- PROTECT VIP'S CAR", "- PROTECT VIP'S CAR"};
                R = new String[]{"PRODUCER", "TEA-M CORP.", "RELEASE 2008", "", "OTHER GAMES", "ESCAPE", "NINJA SCHOOL", "GALAXY BUILDER", "LINE 2", "NEO CHESS", "", "SPECIAL THANKS", "FMA", "E-CHIP MOBILE", "LED-MOBILE", "T-ROCK", "", "VISIT OUR HOMEPAGE", "VECHAI321.XTGEM.COM", "VECHAI321.XTGEM.COM"};
                S = "XFORCE\nTHE PROFESSIONAL\nMILITARY, SECURITY,\nPEACE KEEPING, LAW\nENFORCEMENT COMPANY.\n\nVISION:\nTO SUPPORT SECURITY,\nPEACE, FREEDOM, AND\nDEMOCRACY EVERYWHERE.\n\nCONTROLER:\nUSE THE D-PAD OR�\n4: MOVE LEFT\n6: MOVE RIGHT\n2: MOVE UP\n8: MOVE DOWN\n5: FIRE\n0: SET THE DYNAMIC\n\nREMEMBER CHECK YOUR\nVEHICLE BEFORE YOU\nCHOOSE THE MISSION.\n\nTHE MORE ENEMY YOU\nDESTROYED, THE MORE\nXP POINTS YOU GOT.";
                U = new String[]{"Listen, your task is destroy the train. It will run in next 5 mins.", "yes sir, but how...", "go here to get the dynamite...", "then, put it here and get out...", "now let go..."};
                V = new String[]{"Oh no...", "I will go there now, wait...", "You come, Try to kill him now..."};
                W = new String[]{"done...", "Good job...", "....", "....", "...."};
                X = "Destroy him now";
                Y = "Destroy all fighter in the Airport";
                Z = "Protect him to safe point";
                aa = "Wellcom to XForce team. Many thing waiting for you.";
                ab = "You unlock new vehical. Go to my garage and get it now";
                ac = "Congratulations, you have nothing to unlock.";
                ad = "Congratulations, you have just complete a great mission.";
                H = new String[]{"I see you are back. Good decision!", "Finally you are here! The others started to worry about you.", "Huh!! Later better than never"};
                ae = new String[]{"Hi, my name's Nicholas Craven. Nice to meet you.", "Go out for drink now, ha ha..."};
                af = new String[]{"My name's Xavier Peugeot, call name XP. I will support you.", "No time for relax."};
                ag = new String[]{"Hi, my name's Mia Montaya, I'm a excellent pilot. I wanna make friend with you", "Go out with me please!", "I'm lonely, you make me happy.", "Baby want more time !!!"};
                ah = new String[]{"Hello, I'm Dan Smith, mechanic. I have everything you want.", "Repair your vehical now if you don't want to lose.", "Ha ha. What do you want officer ?..."};
                ai = "Not enough xp";
                aj = "Not enough money";
                ak = "NAME: ";
                al = "PLAY TIME: ";
                am = "GAME COMLETED: ";
                an = "What 's your name ?";
                break;
            case 1:
                f = new String[][]{new String[]{"TIẾP TỤC", "CHƠI MỚI", "LỰA CHỌN", "TÁC GIẢ", "THÔNG TIN", "THOÁT"}, new String[]{"BẢN ĐỒ", "CỬA HÀNG", "GARA", "THÔNG TIN", "", "TRỞ VỀ"}, new String[]{"CHỌN <>", "INFO", "BACK"}, new String[]{"MÁY", "SÚNG", "THÂN", "SỬA CHỮA", "TNT", "", "TRỞ VỀ"}, new String[]{"TRỞ VỀ", "NHIỆM VỤ", "RESTART", "LỰA CHỌN", "VỀ NHÀ"}, new String[]{"NHẠC NỀN: ", "ÂM THANH: ", "RUNG: ", "TỰ BẮN: ", "TRỞ VỀ"}};
                g = new String[]{"TRỞ LẠI", "NHIỆM VỤ", "TUỲ CHỌN", "VỀ CĂN CỨ"};
                h = new String[][]{new String[]{"NHẠC: ", "TIẾNG ĐỘNG: ", "RUNG: ", "ĐIỀU KHIỂN", "NGÔN NGỮ: ", "TRỞ VỀ"}, new String[]{"CHỌN/BẮN: ", "ĐẶT THUỐC NỔ: ", "ĐẶT MÌN: ", "BẮN TỰ ĐỘNG: ", "TRỞ VỀ"}};
                String[] strArr4 = {"CHỌN <>", "CHI TIẾT", "TRỞ VỀ"};
                i = new String[]{"MÁY", "HOẢ LỰC", "THÂN", "SỬA CHỬA", "CHẤT NỔ", "MÌN"};
                String[] strArr5 = {"TỐC ĐỘ", "SỨC CÔNG PHÁ", "GIÁP"};
                j = "BẠN MUỐN MỞ ÂM THANH ?";
                k = "BẠN CÓ MUỐN THOÁT GAME ?";
                l = "TRỞ VỀ CĂN CỨ BẠN SẼ THUA!\nBẠN QUYẾT ĐỊNH VỀ CHỨ?";
                m = "BẠN CÓ MUỐN TẠO PROFILE MỚI ?\nCÁC THÔNG TIN CŨ SẼ BỊ XOÁ.";
                n = "MỞ";
                o = "TẮT";
                p = "CÓ";
                q = "KHÔNG";
                r = "TRỞ LẠI";
                s = "TIẾP";
                t = "CHỌN";
                u = "MUA";
                v = "GARAGE";
                w = "NGHỀ NGHIỆP";
                x = "NÂNG CẤP";
                y = "BẢN ĐỒ";
                z = "NGƯỜI PHÁT TRIỂN";
                A = "GIỚI THIỆU";
                B = "TIỀN: ";
                C = "THƯỞNG: ";
                D = "XP: ";
                E = "GIÁ: ";
                F = new String[]{"H5 ULTIMATE", "CERBERUS III", "APACHE HUSKUS"};
                G = new String[]{"ĐỘNG CƠ DIESEL 180 MÃ LỰC 4-XILANH, VẬN TỐC TỐI ĐA 150KM/H,TRỌNG LƯỢNG : 4.0 TẤN, SÚNG MÁY 5.56MM VÀ TÊN LỬA CHỐNG TĂNG TẦM NHIỆT", "ĐƯỢC TRANG BỊ ĐẠI BÁC HUSUDINS, LASER MẮT THẦN ĐỊNH VỊ, QUAN SÁT ĐÊM HỒNG NGOẠI, HỆ THỐNG TỰ ĐỘNG NẠP ĐẠN, SÚNG MÁY 7.62MM, TÊN LỬA CHỐNG TĂNG VÀ PHÒNG KHÔNG, ĐỘNG CƠ HUSKUDA V12", "ĐỘNG CƠ T780-GE-709C, TÊN LỬA TẦM NHIỆT HYDRA 90 FFAR: KẾT HỢP VỚI HỆ THỐNG AGM-114 HELLFIRE, AIM-92 STINGER, AIM-9 SIDEWINDER "};
                String[] strArr6 = {"TÊN: NICHOLAS CRAVEN \nBÍ DANH: TONIC\nTUỔI: 26\nVAI TRÒ: JEEP DRIVER", "TÊN: XAVIER PEUGEOT\nBÍ DANH: XP\nTUỔI: 35\nVAI TRÒ: TANK DRIVER", "TÊN: MAI MONTAYA\nNICKNAME: BLACK M\nAGE: 23\nVAI TRÒ: PILOT"};
                I = "NHAN PHIM BAT KY";
                J = "NHẤN...";
                K = "DANG TAI...";
                L = "NV HOÀN THÀNH";
                M = "NV THẤT BẠI";
                N = "NHIỆM VỤ";
                O = "TIÊU DIỆT: ";
                P = "THÔNG TIN";
                T = "KHÔNG HỢP LỆ";
                Q = new String[]{"- TIÊU DIỆT TOÀN BỘ QUÂN ĐỊCH", "- PHÁ HUỶ ĐOÀN TÀU HOẢ", "- PHÁ HUỶ TÀU CHIẾN ĐỊCH", "- PHÁ HUỶ TÀU CHIẾN ĐỊCHP\n- GIẾT TRÙM", "- TIÊU DIỆT XE TĂNG ULTRA TANK 34", "- TIÊU DIỆT XE TĂNG LỚN ", "- TIÊU DIỆT ĐỊCH\n- PHÁ HUỶ SÂN BAY", "- BẢO VỆ XE CỦA VIP", "- BẢO VỆ XE CỦA VIP", "- BẢO VỆ XE CỦA VIP"};
                R = new String[]{"SẢN XUẤT", "TEA-M GROUP", "PHÁT HÀNH 2008", "", "GAMES KHÁC", "ESCAPE", "NINJA SCHOOL", "GALAXY BUILDER", "LINE 2", "NEO CHESS", "", "GỞI LỜI CẢM ƠN ĐẾN", "FMA", "E-CHIP MOBILE", "LED-MOBILE", "T-ROCK", "", "THAM QUAN WEBSITE", "VECHAI321.XTGEM.COM", "VECHAI321.XTGEM.COM"};
                S = "XFORCE\nTHE PROFESSIONAL\nMILITARY, SECURITY,\nPEACE KEEPING, LAW\nENFORCEMENT COMPANY.\n\nVISION:\nTO SUPPORT SECURITY,\nPEACE, FREEDOM, AND\nDEMOCRACY EVERYWHERE.\n\nCONTROLER:\nUSE THE D-PAD OR�\n4: MOVE LEFT\n6: MOVE RIGHT\n2: MOVE UP\n8: MOVE DOWN\n5: FIRE\n0: SET THE DYNAMIC\n\nREMEMBER CHECK YOUR\nVEHICLE BEFORE YOU\nCHOOSE THE MISSION.\n\nTHE MORE ENEMY YOU\nDESTROYED, THE MORE\nXP POINTS YOU GOT.";
                U = new String[]{"Alo.. Nhiệm vụ của anh là phá hủy xe lửa chở vũ khí hạt nhân này. Nó sẽ khởi hành trong 5 phút nữa. Nó rất nguy hiểm để tiếp cận và phá hủy, tôi sẽ hướng dẫn anh thật chi tiết", "Vâng, vậy tôi phải làm cách nào", "Hãy đến đây để lấy mìn, đây là loại mìn đặt biệt và cần thiết cho nhiệm vụ này", "Đặt mìn tại đường ray chỗ này, nơi đoàn tau sẽ đi qua. Xong hãy rời khỏi đó.", "Sắp đến giờ rồi, khẩn trương lên. Chúc may mắn..."};
                V = new String[]{"Mẹ kiếp... Hắn đã bỏ chạy mất rồi.", "Đừng lo, em sẽ đến ngay.", "Ah, cô đã đến rồi, hãy đuổi theo ngay, đừng để hắn thoát."};
                W = new String[]{"Ha ha, chúng ta đã thành công rồi.", "Tốt lắm, các anh thật xứng đáng.", "Còn chờ gì nữa, ăn mừng thôi, tôi sẽ đãi chầu nhậu chiều nay.", "Thế còn tăng 2 là gì, ai phụ trách đây", "Tới đó rồi tính, he he..."};
                X = "Hãy giết xe tăng trùm này.";
                Y = "hãy phá hủy tất cả máy bay chiến đấu trong sân bay này. Hãy cẩn thận, chúng sẽ phản công rất dữ dội.";
                Z = "Hãy bảo về xe VIP này đến nơi an toàn.";
                aa = "Chào mừng đến với đội XForce. Chúng tôi đang chờ anh đây.";
                ab = "Anh đã unlock khí tài mới";
                ac = "Chúc mừng, nhưng rất tiếc không còn gì mới nữa :)";
                ad = "Chúc mừng, anh vừa hoàn thành một nhiệm vụ lớn";
                H = new String[]{"Đến trễ còn hơn không. Mời anh ngồi!", "Cuối cùng cũng đến! Tôi tưởng anh chết rồi.", "Huh!! Anh nghĩ anh là ai, ngồi xuống"};
                ae = new String[]{"Chào, mình là Nicholas Craven. Mọi người vẫn gọi là Nick. Rất vui được gặp bạn.", "Xong rồi mình sẽ đi uống cho thật đã nhé, ha ha...", "Mình biết một chổ đánh bida hay lắm, mấy em sắp bi tuyệt vời."};
                af = new String[]{"Tôi là Xavier Peugeot, thường gọi là XP. Tôi sẽ hổ trợ anh.", "Không có thời gian để nghỉ ngơi đâu.", "Tôi không cần đi massa đâu, anh đi một mình đi."};
                ag = new String[]{"Hi, em là Mia Montaya, là một phi công cừ khôi. Em rất muốn làm bạn với anh.", "Tối nay đi chơi với em nhé! hi hi...", "Rất vui khi lại được gặp anh.", "Không yêu đừng nói lời cay đắng !!!"};
                ah = new String[]{"Xin chào, tôi là thợ máy Dan Smith. Tôi luôn có mọi thứ anh muốn.", "Hãy sữa xe ngay nếu anh không muốn bị thất bại.", "Ha ha. Anh muốn gì hả đồng chí ? ..."};
                ai = "Không đủ điểm kinh nghiệm";
                aj = "Không đủ tiền";
                ak = "TÊN: ";
                al = "GIỜ CHƠI: ";
                am = "HOÀN THÀNH: ";
                an = "Anh tên gì ?";
                break;
        }
    }
}
